# Generated by Django 2.1.5 on 2019-01-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlyimage',
            name='gif',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
